name: CI/CD + docker hub + aws ec2 + spring security with jwt

on:
  push:
    branches: [ "deploy" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with maven
        run: mvn clean package -DskipTests
      - name: Login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build docker image
        run: docker build -t abcd/security-jwt .
      - name: Publish image to docker hub
        run: docker push abcd/security-jwt:latest

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Pull image from docker hub
        run: sudo docker pull abcd/security-jwt
      - name: remove the existing container, if there is any
        run: sudo docker rm -f demo-container
      - name: Create and run new container from the image
        run: sudo docker run -d -p 4040:4040 --name demo-container abcd/security-jwt
